### ISSUE TITLE
How to modify strength of SpotClean?

### ISSUE THREAD

**Issue by cf98** [zijianni/SpotClean#14]
Hi SpotClean authors,

I found spotclean effectively reduced the diffusion of some region-specific signals to surrounding regions (I could still see some signals diffusing into surrounding regions). Is it possible to modify the strength of spotclean?

Thanks!

**Comment by zijianni** [comment]
Hello,

SpotClean does not have the ability to control the strength of cleaning - By our model assumption, SpotClean estimates the true cleaned gene expression given observed expression by maximizing the data likelihood. This is a point estimation problem for recovering the unique true expression values, so "modifying the strength of spotclean" is not within our scope.

I see your concern that after SpotClean you are still seeing positive expression of marker genes in surrounding regions where they are not supposed to express. 

- First, I don't expect that SpotClean will make any non-zero spots become zero. There is no sparsity regulation terms in our model as it significantly complicates the EM steps. 

- Second, SpotClean does not rely on any external biological information about whether a gene should or should not be expressed in certain tissue spots, so the SpotClean estimation is not guaranteed to perfectly aligns with the biological expectations.

- Last, for regions that a gene is not expected to express, it's hard to tell if it was SpotClean who under-cleaned these spots, or if there are actually real biological signals of this gene in these spots. It's also possible that external contaminations during tissue preparation introduce unwanted signals into these regions.

Happy to further discuss if you have follow-up questions.

**Comment by zijianni** [comment]
Unfortunately that is not feasible - SpotClean relies on information from background spots to infer spot swapping distribution. After SpotClean, all UMI counts from background spots have been re-assigned to tissue spots. There is no information from background spots for a second round of SpotClean.

**Comment by zijianni** [comment]
In order to have cleaner result, you can consider adding some global filtering on the cleaned expression, e.g. change values <1 to be 0. Note that this is not a standard step and might negatively affect downstream analyses (we didn't validate it so I can't tell).

**Comment by cf98** [comment]
> In order to have cleaner result, you can consider adding some global filtering on the cleaned expression, e.g. change values <1 to be 0. Note that this is not a standard step and might negatively affect downstream analyses (we didn't validate it so I can't tell).

Thank you!
