### ISSUE TITLE
How to run with large datasets in limited memory?

### ISSUE THREAD

**Issue by ZeroLi-Bio** [zijianni/SpotClean#18]
Hello,

Thanks for the software.
I have a datasets of around 80k spots in tissue. I tried run decontamination on a 1000Gb memory machine, but met errors below: 
```
Loading required package: stats4
Loading required package: BiocGenerics

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min


Attaching package: ‘S4Vectors’

The following object is masked from ‘package:utils’:

    findMatches

The following objects are masked from ‘package:base’:

    expand.grid, I, unname

Filtered out 30107 genes with average expressions below or equal to 0.1.
2023-06-05 09:24:16.913087 Start.
Kept 142 highly expressed or highly variable genes.
2023-06-05 09:32:47.415611 Estimating contamination parameters...
  |                                                                      |   0%
 *** caught segfault ***
address 0x2b1118048000, cause 'invalid permissions'

Traceback:
 1: base::crossprod(x, y)
 2: crossprod(W_y)
 3: crossprod(W_y)
 4: unname(crossprod(W_y))
 5: .SpotClean(raw_data = raw_data, slide = slide, gene_keep = gene_keep,     maxit = maxit, tol = tol, candidate_radius = candidate_radius,     kernel = kernel, verbose = verbose)
 6: spotclean.SummarizedExperiment(slide_obj, maxit = 10, candidate_radius = 20)
 7: spotclean(slide_obj, maxit = 10, candidate_radius = 20)
An irrecoverable exception occurred. R is aborting now ...
/opt/gridengine/default/spool/cngb-gpu-f15-1/job_scripts/2281748: line 2: 71808 Segmentation fault      (core dumped) /jdfssz1/ST_SUPERCELLS/P21Z10200N0134/USER/lizeyu/00.software/Miniconda3/envs/r430/bin/Rscript /jdfssz1/ST_SUPERCELLS/P21Z10200N0134/Project/25.ESCA/lizeyu/27.SpotClean/spotclean.run.R
```
It looks like caused by memory size limit. Do you have advice about running on this large data?
Can I downsample in-tissue spots into several parts to run seperately and later merge the results into one?

Thank you a a lot!

**Comment by zijianni** [comment]
Hi @ZeroLi-Bio , a dataset of 80k tissue spots is not a common input for SpotClean, as it was primarily designed for Visium data, which contains at most 5k spots.

For non-Visium data, rigorously speaking, the nature of spot swapping has not been scientifically verified (though we believe it is a common artifact across many protocols, and this is not hard to check - just check what's in the background spots, which shouldn't contain any expression), and there is no guarantee that the model assumption of SpotClean on spot swapping still holds true. Please be careful if you decide to apply SpotClean to non-Visium data.

For your idea of randomly partitioning spots into subsets (if I understand it correctly), I think that's a smart direction to explore. However, our model assumes that each spot contains spot-swapped expressions from all nearby spots. If only a subset of nearby spots are provided, the effect from the rest nearby spots are not modelled, and it could result in incorrect estimations.
