### ISSUE TITLE
Error in createSlide(), 'barcodes in count matrix do not match barcodes in slide info'

### ISSUE THREAD

**Issue by BartBryant** [zijianni/SpotClean#19]
Hi SpotClean

First, thanks for this awesome tool, can't wait to implement it into my research program.

I am following the SpotClean vignette.Rmd tutorial 
https://github.com/JEFworks-Lab/STdeconvolve/blob/package/vignettes/vignette.Rmd

At the 'visualize data' section I get an error message stating 'Barcodes in count matrix do not match barcodes in slide information' (see screenshot).  
![image](https://github.com/zijianni/SpotClean/assets/135715545/24661eb2-2052-47c3-9cc0-c7df3329e2fd)

Also my first time using GitHub, so please excuse my nube-newness.

Best
Bart

**Comment by zijianni** [comment]
Hi Bart,

Thanks for your intestests in using SpotClean! Based on the error message, it indicates the barcodes in your input gene expression matrix does not match the barcodes in the slide information. Barcodes in the input expression matrix are its column names. Barcodes in the slide information is a dataframe column. Please check if they match each other.

From your screenshot I've actually seen the issue - you are supposed to use the unfiltered expression matrix, which contains both tissue spots and background spots. You can update line 25 of your code to load the unfiltered expression matrix (its file name should be something like `raw_feature_bc_matrix`) and retry.

Best,
Zijian

**Comment by BartBryant** [comment]
Hi Zijian,

I changed the expression matrix with 'raw_feature_bc_matrix' but still got same error (see screenshot). 

For the first comment on checking the data.frames for expression matrix and slide-info, how best to check the objects to make sure they match?  
<img width="1512" alt="Screenshot 2023-06-27 at 1 43 12 PM" src="https://github.com/zijianni/SpotClean/assets/135715545/aac49e9d-7d51-472d-afb2-99c0a23d5538">

Thanks for your help,
Bart

**Comment by zijianni** [comment]
To get the barcodes from the expression matrix, you can try `rownames(D1_raw)`. To get the barcodes from the slide info, you can try `D1_slide_info$slide$barcode`. Then it becomes a comparison of two vectors.

**Comment by zijianni** [comment]
Ah, sorry it should be `colnames()` instead of `rownames()`. The row names are genes and column names are barcodes.

**Comment by BartBryant** [comment]
ok, yeah that suggestion gave barcodes
looks like they do not match (see screenshot)
is this a SpaceRanger output issue then, or can i use some package within R to make the objects match?
________________________________
From: Zijian Ni ***@***.***>
Sent: Wednesday, June 28, 2023 10:06 AM
To: zijianni/SpotClean ***@***.***>
Cc: Bryant, William01 ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [zijianni/SpotClean] Error in createSlide(), 'barcodes in count matrix do not match barcodes in slide info' (Issue #19)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
CAUTION: EXTERNAL SENDER

This email originated from an external source. Please exercise caution before opening attachments, clicking links, replying, or providing information to the sender. If you believe it to be fraudulent, contact the AU Cybersecurity Hotline at 72-CYBER (2-9237 / 706-722-9237) or ***@***.***

________________________________

Ah, sorry it should be colnames() instead of rownames(). The row names are genes and column names are barcodes.

**Comment by BartBryant** [comment]
<img width="1512" alt="Screenshot 2023-06-28 at 10 15 39 AM" src="https://github.com/zijianni/SpotClean/assets/135715545/d2ebb798-3c06-4816-aff8-c13cf7161ad5">

**Comment by zijianni** [comment]
You can check it in a more programmatically, e.g. some use cases in https://statisticsglobe.com/compare-vectors-and-find-differences-in-r. If they are really different, it's likely the nature of your data. 

There is another issue that could be related #15 . If that's the case, consider filtering the slide info dataframe to match the barcodes appeared in the expression matrix.

**Comment by zijianni** [comment]
Closing this issue as no further communications were added.
