### ISSUE TITLE
Error in convertToSeurat function, "Error in FUN(left, right) : non-numeric argument to binary operator"

### ISSUE THREAD

**Issue by maki8080** [zijianni/SpotClean#21]
Hi, 

Thanks for the great software.
I want to convert my slide object to seurat object. When I run the convertToSeurat function, I get the following error and it does not work.

```
set.seed(1234)
raw <-SpotClean::read10xRaw("B1_SRT/raw.data")
image <- SpotClean::read10xSlide(tissue_csv_file = "B1_SRT/image/tissue_positions_list.csv",
                      tissue_img_file = "B1_SRT/image/tissue_lowres_image.png",
                      scale_factor_file = "B1_SRT/image/scalefactors_json.json")

obj <- createSlide(count_mat = raw, slide_info = image)
visualizeSlide(slide_obj = obj)
p1 <- visualizeHeatmap(obj,rownames(obj)[1])
decont_obj <- spotclean(obj)
seurat_obj <- SpotClean::convertToSeurat(slide_obj = decont_obj, image_dir = "B1_SRT/image")

> seurat_obj <- SpotClean::convertToSeurat(slide_obj = decont_obj, image_dir = "B1_SRT/image")
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Error in FUN(left, right) : non-numeric argument to binary operator
```
If anyone have any idea about it, please let me know.

Thank you a lot.

Maki

**Comment by maki8080** [comment]
Hi, 
The reason for the error may have been that image.seurat@coordinates obtained by input in the Read10X_Image function was character. I converted it to numeric.

``
# create Seurat object
object.new <- CreateSeuratObject(assay(decont_obj), assay = "Spatial")
# load image and add to Seurat object
image.seurat <- Read10X_Image(image.dir = "B1_SRT/image", filter.matrix = T)
image.seurat@coordinates$imagerow <- as.numeric(image.seurat@coordinates$imagerow)
image.seurat@coordinates$imagecol <- as.numeric(image.seurat@coordinates$imagecol)
ts_coord <- GetTissueCoordinates(image.seurat)

nrow(ts_coord) == ncol(object.new) # TRUE
image.seurat <- image.seurat[Cells(x = object.new)]
DefaultAssay(object = image.seurat) <- "Spatial"
object.new[["slice1"]] <- image.seurat
object.new

``
Is it OK to proceed with the downstream analysis with the seurat object obtained this way?

Thanks!

Maki

**Comment by zijianni** [comment]
Thanks for identifying the issue! Yes, you can directly export the decontaminated expression matrix from SpotClean into Seurat in different ways.
