### ISSUE TITLE
Ensembl IDs to Gene Names

### ISSUE THREAD

**Issue by shahrozeabbas** [zijianni/SpotClean#27]
Sorry for the many questions, but I decided to open a separate issue for this in case anyone else has the same problem. I noticed that running `SpotClean` seems to convert gene names into Ensembl IDs. Is there a way to avoid this or change back after running `SpotClean`?

Thanks.

**Comment by JoyOtten** [comment]
I found this strange as well. Ofcourse you always can convert the ensembl ID's back to gene names with Biomart. However, I would much rather like that they update the package and leave the conversion of the gene ID to ensembl ID out of it.
