### ISSUE TITLE
BayesSpace after SpotClean

### ISSUE THREAD

**Issue by JihyunKiminGithub** [zijianni/SpotClean#5]
Dear developers,

I want to use BayesSpace for clustering after spotclean like you mentioned at your paper.
Can I please know how did you process spotclean results for the BayesSpace input?
I am confusing since BayesSpace requires us to use count assay and we need to normalize & run pca & run umap.
Can I just use spot clean decont assay instead of counts assay and log-normalize & run pca to be used as a BayesSpace input file??

Thank you,
Jihyun

**Comment by JihyunKiminGithub** [comment]
#Any example code would be appreciated#
#Codes following returns error message so that I am wondering how did you processed this#

s1 <- readRDS("./spotclean_visiumobj.rds")
s1_sc <- as(s1, "SingleCellExperiment")
s1_sc@assays@data$counts <- s1_sc@assays@data$decont
s1_sc <- logNormCounts(s1_sc)
s1_sc <- runPCA(s1_sc)
s1_sc <- spatialPreprocess(s1_sc, platform="ST", n.HVGs=2000)
s1_sc <- spatialCluster(s1_sc, q=10, nrep=100, burn.in=10)

**Comment by zijianni** [comment]
Hi @JihyunKiminGithub ,

Can you show me the exact error message you got? 

FYI, code to reproduce the BayesSpace results in our paper can be found here: https://github.com/zijianni/codes_for_SpotClean_paper/blob/main/colorectal_cancer/colorectal_cancer.Rmd

Best,
Zijian

**Comment by zijianni** [comment]
I'm closing this issue now. Feel free to reopen if you have further questions.
