### ISSUE TITLE
install for R <= 4.1.3

### ISSUE THREAD

**Issue by alikhuseynov** [zijianni/SpotClean#6]
Hi there, 
is it possible to install your package for R version <= 4.1.3 ?

`ERROR: this R is version 4.1.3, package 'SpotClean' requires R >= 4.2.0`

Many Thanks

**Comment by alikhuseynov** [comment]
just solved via `devtools::install_github("zijianni/SpotClean", ref = "devel")`

**Comment by zijianni** [comment]
Glad you figured it out! We set the restriction for using the latest R version as required by Bioconductor. Our package should still work under reasonably earlier R versions.

**Comment by alikhuseynov** [comment]
Hi, thanks. I could install it under R 4.1.3 and 4.2.0 in several conda env on a cluster. However on Rstudio server under R 4.0.2 it didn't work.

`Error: object ‘spatialData’ is not exported by 'namespace:SpatialExperiment'`

I think it has to do with the version of SpatialExperiment, that I cannot update from Bioconductor, nor from their github repo.
```
Biobase::package.version("SpatialExperiment")
[1] "1.0.0"
```
