### ISSUE TITLE
Adapt to Spaceranger 2.0 output

### ISSUE THREAD

**Issue by jeramand** [zijianni/SpotClean#7]
Hello,

the ouput of the newest version of Spaceranger 2.0 changed slightly ([see Release Notes](https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/release-notes)).
The file `tissue_positions_list.csv` was renamed to `tissue_positions.csv` and a header was added to the CSV file.

Changing `header = FALSE` to `TRUE` for `tissue_csv_file` in `read10xSlide` worked for me (but of course would break backwards compatibility).

Thanks
Jérémy

**Comment by zijianni** [comment]
Hi @jeramand ,

Thanks for reporting this! I've pushed a quick and dirty fix for it. If you encounter any further issues due to incompatibility with Space Ranger V2, feel free to let me know.

Best,
Zijian
